[FIX] workflow actions

diff --git a/.github/workflows/download.yml b/.github/workflows/download.yml
--- a/.github/workflows/download.yml
+++ b/.github/workflows/download.yml
@@ -8,28 +8,37 @@ jobs:
   download-and-commit:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout repo
-        uses: actions/checkout@v3
-
-      - name: Set up Python
-        uses: actions/setup-python@v4
+      - uses: actions/checkout@v3
+      - uses: actions/setup-python@v6
         with:
-          python-version: '3.x'
-
+          python-version: '3.13' 
+          
       - name: Run download script
-        run: |
-          python main.py
+        run: python main.py
 
-      - name: Commit and Push changes
+      - name: Configure Git
         run: |
-          git config user.name "github-actions"
-          git config user.email "actions@github.com"
-          
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
+
+
+      - name: Commit and Pull
+        run: |
           git add downloads/
+          git diff --cached --quiet || (git commit -m "[UPDATE] downloaded files via Python")
+          git pull --rebase --autostash origin master
           
-          if git diff --cached --quiet; then
-            echo "No new or changed files to commit."
-          else
-            git commit -m "Update downloaded files via Python script"
-            git push origin HEAD:${{ github.ref }}
-          fi
+
+      - name: Push changes
+        run: |
+          n=0
+          until [ $n -ge 5 ]
+          do
+            git push origin HEAD:master && break
+            n=$((n+1))
+            echo "Push failed. Retrying in 5 seconds... ($n/5)"
+            sleep 5
+          done
+
+   
